import cx_Freeze

executables = [cx_freeze.Executable("main.py")]

cx_freeze.setup(
    name="Legend Rush",
    options={"build_exe": {"packages":["pygame",
                                       "json"],
                           "included_files":["blob.py",
                                             "constants.py",
                                             "heart.py",
                                             "imp.py",
                                             "level.py",
                                             "menu.py",
                                             "platforms.py",
                                             "player.py",
                                             "spritesheet.py",
                                             "terrain.py",
                                             "tools.py",
                                             "level_data/level1/data.json",
                                             "level_data/level1/tiles.png",
                                             "level_data/level1/types.png",
                                             "level_data/level2/data.json",
                                             "level_data/level2/tiles.png",
                                             "level_data/level2/types.png",
                                             "level_data/level3/data.json",
                                             "level_data/level3/tiles.png",
                                             "level_data/level3/types.png",
                                             "level_data/level4/data.json",
                                             "level_data/level4/tiles.png",
                                             "level_data/level4/types.png",
                                             "level_data/level5/data.json",
                                             "level_data/level5/tiles.png",
                                             "level_data/level5/types.png",
                                             "level_data/level6/data.json",
                                             "level_data/level6/tiles.png",
                                             "level_data/level6/types.png",
                                             "level_data/colorpalette.png",
                                             "level_data/typepalette.png",
                                             "resources/icon.ico",
                                             "resources/images/background_01.png",
                                             "resources/images/blob2.png",
                                             "resources/images/buttons.png",
                                             "resources/images/hearts.png",
                                             "resources/images/Imp.png",
                                             "resources/images/player.png",
                                             "resources/images/terrain.png",
                                             "resources/images/title.png",
                                             "resources/images/tools.png",
                                             "resources/sounds/Attack Sound.wav",
                                             "resources/sounds/Death Sound.wav",
                                             "resources/sounds/Jump Sound.wav",
                                             "resources/sounds/Flight.mp3"]}}
    
    )
